#if($DownloadCollectionReport)
Feature: Download of collection reports done by the system
As a researcher
I want to download a collection report
So I can have a way to locally save reports generated by the system

#CONTROLLER

Scenario: File generation
Given that there were collections on at least one residue generator on month "11"
And I have created a report 
When the system receives a request to create an CSV file of the report
Then a CSV file is sent to the client 


Scenario: Error in file generation
Given that there were no collections made on at least one residue generator on month "12"
And I there are no reports in the database 
When the system receives a request to create an CSV file of the current report
Then a error is given

#GUI


Scenario: Download a report
Given I am at the Relatorios Page
When I select the "Download CSV" option
Then I should get the CSV file of the report





#end